# Generated by Django 4.0.3 on 2022-03-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='fund',
        ),
        migrations.AddField(
            model_name='investor',
            name='fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.fund'),
        ),
    ]
